# config
cover: //

logo: /img/avatar.jpg

bio: "Rick likes to software develop. Rick likes to write. Rick likes dance music. Rick likes to travel and take blurry photos. Rick plays soccer all the time. He also refers to himself in third person sometimes."

fancybox: true

google_analytics: true

# Content
excerpt_link: Read More

# Miscellaneous
rss:
